apiVersion: chaos-mesh.org/v1alpha1
kind: KernelChaos
metadata:
  name: kernel-chaos-example
  namespace: chaos-testing
spec:
  mode: one
  selector:
    labelSelectors:
      app: sf4-animals-demo
  failKernRequest:
    callchain:
        - funcname: "__x64_sys_mount"
    failtype: 0
